"""Cambiar membresia de String a Integer

Revision ID: 16660285be37
Revises: a1b893be4d72
Create Date: 2025-06-22 01:19:45.242497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16660285be37'
down_revision = 'a1b893be4d72'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE cliente ALTER COLUMN membresia TYPE INTEGER USING membresia::integer;")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('membresia',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
